### PR TITLE
update JSON Forms to 3.2.0-beta.0

### PR DESCRIPTION
**Pull request by LukasBoll**

### CODE REVIEW

**Comment by LukasBoll** [comment]
Hi @sdirix 
`npm run serve` is working, but I still have problems with the build step

**Comment by sdirix** [comment]
Can you post the error message? Could it be related to this issue https://jsonforms.discourse.group/t/custom-renderers-not-rendering/1250/3?

**Comment by LukasBoll** [comment]
> Can you post the error message? Could it be related to this issue https://jsonforms.discourse.group/t/custom-renderers-not-rendering/1250/3?

I don't think it´s related, The build step already throws an error. I am getting this error message:

js/app.9d18be5c.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\terser-webpack-plugin\dist\index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\terser-webpack-plugin\dist\index.js:160:259)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1342:27)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compiler.js:675:18
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1253:28)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compiler.js:672:17
    at _done (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1185:12
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

 error 

js/chunk-vendors.09f8ad1e.js from Terser
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\terser-webpack-plugin\dist\index.js:217:37
    at Array.forEach (<anonymous>)
    at TerserPlugin.optimizeFn (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\terser-webpack-plugin\dist\index.js:160:259)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.seal (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1342:27)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compiler.js:675:18
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1253:28)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compiler.js:672:17
    at _done (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at eval (eval at create (C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:22)
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1185:12
    at C:\Users\lukas\EclipseSource\jsonforms-vue-seed\node_modules\webpack\lib\Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

 ERROR  Build failed with errors.

**Comment by sdirix** [comment]
Merged via https://github.com/eclipsesource/jsonforms-vue-seed/pull/20

**Pull request closed without merging**
